name: Upload content
on:
  workflow_call:
    secrets:
      API_TOKEN_GITHUB:
        required: true

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / UploadContent / Drogon'
    # Action dashboard identified by 'Upload content'
    # Requirement settings identified as 'UploadContent / Drogon'
    name: Drogon
    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        ref: ${{ github.head_ref }}
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN
        fetch-depth: 0  # otherwise, there would be errors pushing refs to the destination repository

    - name: Copy latest cache files  # Actual data files should dump to this folder from other workflows
      run: |
        cp /mnt/backup/dandi/dandiarchive-logs-parser-cache/dandi_s3_log_parser/region_codes_to_coordinates.json \
        /mnt/backup/dandi/dandiarchive-logs-cody/aaccess-summaries/region_codes_to_coordinates.json

    - name: Add and commit files
      run: |  # `|| true` below to skip if nothing changed from pre-commit
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *
        git commit -m "update S3 log summary content" -a || true